### ISSUE TITLE
Replace hardcoded values scattered around the project with constants

### ISSUE THREAD

**Issue by Matthew-Bonner** [ASP-NET-MVC-Boilerplate/Templates#119]
There are various hard-coded values such as author, phone number, address, and e-mail address which are scattered around the project when it is first created.

When initially setting up a project you have to perform a search for the following and change them:

- Muhammad Rehan Saeed
- Rehan Saeed
- @RehanSaeedUK
- One Microsoft Way
- Redmond, WA 98052-6399
- 425.555.0100
- Support@example.com
- Marketing@example.com
- ASP.NET MVC Boilerplate
- 1 Street Name
- City
- SW1 1SW
- United Kingdom
- email@example.com
- example@email.com
- 111-222-333-444
- 51.5286417
- -0.1015987
- http://rehansaeed.com

The worst examples of this are the Contact.cshtml and About.cshtml page.

I think creating a Branding class in the constants directory which contains the company name, address, phone number and e-mail address would help. It would help to also add an Author constant to the Application class so that the author can be changed easily.

**Comment by Matthew-Bonner** [comment]
This is the constants I would add to the Branding class:
CompanyName = "ASP.NET MVC Boilerplate";
AddressLine1 = "1 Street Name";
AddressLine2 = "City";
AddressLine3 = "SW1 1SW";
AddressLine4 = "United Kingdom";
AddressLat = 51.5286417;
AddressLong = -0.1015987;
EmailAddress = "email@example.com";
SupportEmailAddress = "email@example.com";
MarketingEmailAddress = "email@example.com";
PhoneNumber = "111-222-333-444";
Twitter = "@RehanSaeedUK";
Website = "http://rehansaeed.com";

And for the Application class I would have the following constants:
Name = "Tech Company Analysis";
ShortName = "Tech Company Analysis";
AuthorFirstName = "Tech Company";
AuthorLastName = "Analysis";
Author = AuthorFirstName + " " + AuthorLastName;

Based on the code I've seen.

I can create a pull request with these changes if you agree to them, otherwise we can discuss this change further if you want.

**Comment by RehanSaeed** [comment]
This could be placed in config.json. I'm at a wedding, will take a look later.

**Comment by RehanSaeed** [comment]
Sorry for the delay, I've only now had time to look into this. Would really appreciate a PR, it's a great idea BTW. What sections do you envisage adding to config.json. I am thinking:

```
// Existing Section
"AppSettings": {
RootUrl = "http://example.com"
ThemeColour = "#1E1E1E"
}

// New Section. Should this live under AppSettings or the root I wonder?
"ContactSettings": {
CompanyName = "ASP.NET MVC Boilerplate"
AddressLine1 = "1 Street Name"
AddressLine2 = "City"
AddressLine3 = "SW1 1SW"
AddressLine4 = "United Kingdom"
AddressLat = 51.5286417
AddressLong = -0.1015987
EmailAddress = "email@example.com"
PhoneNumber = "111-222-333-444"
Twitter = "@Example"
}
```

My name should also probably not be plastered all over the place, so I've swapped it with example where necessary too. Also we need to bear in mind that the Contact page is optional, so some of these config properties will not exist if that feature is turned off. Thoughts?

**Comment by RehanSaeed** [comment]
Added to the new GitHub Projects section as a To-Do item.
