### ISSUE TITLE
RedirectToCanonicalUrlAttribute - Make Lowercasing of QueryString Optional

### ISSUE THREAD

**Issue by Ketrex** [ASP-NET-MVC-Boilerplate/Templates#128]
The RedirectToCanonicalUrlAttribute produces a lowercase URL. This works until the user implements case-sensitive query strings (example: password reset codes). The attribute is setting query string values to lowercase as well and causing case-sensitive evaluations to fail.

`http://somedomain.com/page?resetcode=CeT938$`
is then converted to:
`http://somedomain.com/page?resetcode=cet938$`

This will fail when the query string parameter is case sensitive.

Query strings are often mixed-case and necessarily to be so. The query string should not be changed or evaluated by this attribute.

**Comment by Ketrex** [comment]
Nevermind, I just came across the NoLowercaseQueryString attribute.

**Comment by Ketrex** [comment]
I'm going to reopen this just as a suggestion. I think the default behavior should to be to allow query strings to be mixed-case. In my experience, more often than not, I want to preserve the case of the query string. It can be quite the gotcha when instituting a password reset routine involving a case-sensitive reset code (as is implemented with the default implementation of ASP.NET Identity) to have this reset routine fail due to lower-casing.

**Comment by RehanSaeed** [comment]
Perhaps the default should be configurable, I find that most of the time mixed case is not required, the ASP.NET Identity case is the major exception to the rule that everyone comes across.

**Comment by Ketrex** [comment]
I think the case often doesn't matter for the keys in a querystring, but most of the time, the value does matter. It's not uncommon to have querystrings like this  `http://someurl?FirstName=Bob&LastName=Schmidt&City=New York` in this case, lowercasing those values would definitely create unexpected behavior in addition to the conflict with reset codes mentioned previously. I agree making it configurable would be best, but I would consider making the default mixed-case.

**Comment by RehanSaeed** [comment]
Added to Project To-Do
