### ISSUE TITLE
Add Check to Make Sure .NET Core SDK is Installed

### ISSUE THREAD

**Issue by VeXHarbinger** [ASP-NET-MVC-Boilerplate/Templates#131]
I created a new project that used the .net (not core) framework with none of the JS add-ons. (lint etc..)   
When I attempt to publish the project with out making any changes I get this error.

> C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error : No executable found matching command "Runs"

Any idea what this is looking for or how to resolve it?  I can give you more information on the options I selected if needed.

**Comment by VeXHarbinger** [comment]
I downloaded the GIT solution I got the missing .Net Core SDK alert.  Installing that resolved my publish issue.  So I guess there needs to be a check/alert in the sites using the template
https://github.com/aspnet/Tooling/blob/master/known-issues.md#missing-sdk

**Comment by RehanSaeed** [comment]
So you did a right click on the project and clicked publish to get that error. By your second comment, it looks like you did not have .NET Core SDK installed. There is a comment in the ReadMe about pre-requisites. I suppose I could add some kind of check.

**Comment by RehanSaeed** [comment]
This issue has been added to the To-Do list in https://github.com/ASP-NET-MVC-Boilerplate/Templates/projects

**Comment by VeXHarbinger** [comment]
I fully admit I could have missed the notation where it's listed as a requirement, but if it is you are correct in marking it as PEBCAK.  It was just that locally everything ran like a charm, the error only occurred during any publish action.  I tried to google the error message, but found no results that pointed me in the right direction to triage the issue.  I considered the possibility that I mis-configured the app, so created a new empty project with the template and it occurred again.  It was only when I downloaded the git to see if I could track down the call to see if I had coded something incorrectly, that the git solution enlightened me as to the error in my ways when it prompted me to install the missing component upon opening.  I just thought if my project prompt me in the same manor when I created or (re)opened it, it could save another developer some heartache since typically they won't encounter this issue till they've coded enough of a project to be ready to publish.  

This reminds me of the immortal words of Douglas Adams;
> A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.

**Comment by VeXHarbinger** [comment]
Oh and since I'm already writing to you, I'd just like to say thank you for all your hard work.  It's a wonderful template, and I've been excited to trace down all the functionality incorporated with-in to better understand the hows and whys of what it consists of.

**Comment by RehanSaeed** [comment]
I'm partial to a bit of Douglas Adams :)

Unfortunately, Microsoft does not give very good built-in tools to do this check, so I'd have to write some code to do this and then show some kind of message box with a link to download the tools.

This issue may go away as the new way to create a project from a template moves to the new `dotnet new` CLI command. I'm speaking to some Microsoft guys soon about it, will ask them how they handle the SDK not being installed too.
