### ISSUE TITLE
Project with spaces in the name will not build

### ISSUE THREAD

**Issue by Ketrex** [ASP-NET-MVC-Boilerplate/Templates#133]
I created a new ASP.NET MVC Boilderplate Core 1.0 project using the extension and named it "Boiler Test." I accepted the project defaults, ran 'dotnet restore' followed by 'dotnet build.'

The build fails with the following error:

`F:\src\local\Boiler Test\Boiler Test\error CS2001: Source file 'F:\src\local\Boiler Test\Boiler Test\Test.deps.json' could not be found.`

Creating a project with the name 'BoilerTest' works just fine.

**Comment by RehanSaeed** [comment]
Does VS even let you do this? If so, then that's crazy, a project name should never have a space in it.

**Comment by Ketrex** [comment]
While it's not best practice for sure, developers have always been able to put spaces in the csproj and xproj project names. "Newbies" definitely put spaces in the project names to make the titles more human readable, so it's not uncommon and is perfectly valid.
![image](https://cloud.githubusercontent.com/assets/5253527/19732221/56a21ba6-9b5d-11e6-8d31-31103447cd79.png)

**Comment by RehanSaeed** [comment]
Noted and added to the backlog. See the projects tab.

**Comment by RehanSaeed** [comment]
I just tested this with a normal ASP.NET Core project and it produced the same error! I think this is a VS tooling issue. I'd advise you to raise an issue in the ASP.NET MVC GitHub "Tooling" repository.
