### ISSUE TITLE
IIS Express(Production) Debug

### ISSUE THREAD

**Issue by JsonRoob** [ASP-NET-MVC-Boilerplate/Templates#134]
[23:07:51] Starting 'test'...
ReferenceError: Can't find variable: require
   in global code at file:///f:/Projects/latestcore1/latestcore1/bower_components/sinon/lib/sinon.js:11
[23:07:54] 'test' errored after 3.54 s
[23:07:54] Error in plugin 'gulp-mocha-phantomjs'
Message:
    test failed. phantomjs exit code: 1

**Comment by RehanSaeed** [comment]
Taking a look.

**Comment by RehanSaeed** [comment]
I'm working on removing Bower completely and switching to NPM on it's own. This will get fixed while doing this anyway.
