### ISSUE TITLE
Any plans to integrate SimpleInjector DI  container?

### ISSUE THREAD

**Issue by timematcher** [ASP-NET-MVC-Boilerplate/Templates#136]
Hi Rehan, Hope that you are well.

Do you have any plans to integration SimpleInjector? 

[Simple Injector Website](https://simpleinjector.org/index.html)

I am not sure if you are taking feature requests and I wasn't sure if I could post this as issue.
If you decide to fulfill this request, maybe you can provide two optons

1. Built in dependency resolver 
2. SimpleInjector 

Here is an article with code that is relevant if you decide on implement this as optional DI container.
[working-around-the-asp-net-core-DI-abstraction](https://simpleinjector.org/blog/2016/07/working-around-the-asp-net-core-di-abstraction/)

**Simple Injector Benchmarks:**
[SimpleInjector Benchmarks](http://www.palmmedia.de/blog/2011/8/30/ioc-container-benchmark-performance-comparison)

**Asp.NET MVC Core Integration Guide**
[ASP.NET Core Integration guide](http://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html)

It would really be great if there were an option to integrate this DI container as an alternate to ASP.NET MVC Core built-in DI resolver/injector/container.

Thanks
Awais

**Comment by RehanSaeed** [comment]
There are 101 DI containers out there. The big ones are Autofac, Ninject, Castle etc. Never heard of this one. No plans to do this, we might in the future but there is too many other more interesting features we need to add (See the projects tab).
