### ISSUE TITLE
Any plans to use URL rewrite middleware to redirect to https?

### ISSUE THREAD

**Issue by os1r1s110** [ASP-NET-MVC-Boilerplate/Templates#137]
Sorry if this is the wrong place to post this question as this is not a real "issue" per se. 

I'd like to know if you plan on adding the url rewriting middleware to redirect to https and canonical urls instead of the actual implementation, do you think it would be a useful thing to add?

**Comment by RehanSaeed** [comment]
There is one in ASP.NET Core 1.1. Redirect to Canonical URL middleware is planned. See the Projects tab, you can see it there.

**Comment by os1r1s110** [comment]
Ahah yeah that's what I meant I was asking  if you planned on using it in your template.
