### ISSUE TITLE
Task Test in gulpfile fails due to space in directory

### ISSUE THREAD

**Issue by momoski** [ASP-NET-MVC-Boilerplate/Templates#139]
I get an error when the Task Runner is running Test from the Gulpfile.

```
[22:00:19] Starting 'test'...
'C:\Users\myname\documents\visual' is not recognized as an internal or external command,
operable program or batch file.
[22:00:19] 'test' errored after 35 ms
[22:00:19] Error in plugin 'gulp-mocha-phantomjs'
Message:
    test failed. phantomjs exit code: 1
Process terminated with code 1.
```

I don't know what to change in the gulpfile in order to handle spaces in the path.

**Comment by RehanSaeed** [comment]
Looks like a bug in `gulp-mocha-phantomjs`. I would raise an issue on their GitHub page and maybe use a path without a space in the mean time.
