### ISSUE TITLE
Issue on Creating New Core MVC Project

### ISSUE THREAD

**Issue by Godminders** [ASP-NET-MVC-Boilerplate/Templates#141]
![image](https://cloud.githubusercontent.com/assets/13841076/21579105/715eaf20-cf6c-11e6-9475-cbb870e74ed1.png)

Installed into a clean installation of Visual Studio 2015 with Update 3 and .Net Core 1.1.

**Comment by RehanSaeed** [comment]
In C:\Program Files\dotnet\sdk you need 1.0.0-preview2-1-003177 to be there, or if you have later versions (If you install VS2017 you will get a newer version), then you need a global.json next to your .sln file like this to point to the correct version of the runtime:

{
  "projects": [ "Source", "Tests" ],
  "sdk": {
    "version": "1.0.0-preview2-1-003177",
    "runtime": "clr",
    "architecture": "x64"
  }
}

**Comment by RehanSaeed** [comment]
Feel free to re-open if I've not answered your question.
