### ISSUE TITLE
Consider adding ES6 support

### ISSUE THREAD

**Issue by dotnetshadow** [ASP-NET-MVC-Boilerplate/Templates#144]
Hi there,

Great work with the template.

I thought it would be cool if you could add ES6 support, I believe gulp has gulp-babel that can transpile ES6 -> ES5?

https://onsen.io/blog/trying-out-javascript-es6-using-babel/

**Comment by RehanSaeed** [comment]
This is planned, although we should give an ES6/TypeScript choice.

**Comment by RehanSaeed** [comment]
Have added a [TODO](https://github.com/ASP-NET-MVC-Boilerplate/Templates/projects/2) to implement a Babel feature as opposed to the current TypeScript feature we have already.

**Comment by dotnetshadow** [comment]
Thank you that would be great,
I didn't see the TODO list before I like it

Just so you know jquery validation plugin now includes the minified version in npm if you use package 1.16.0

**Comment by RehanSaeed** [comment]
Cool! I actually submitted the PR to add that.

**Comment by RehanSaeed** [comment]
Updated to 1.16.0
