### ISSUE TITLE
ASP MVC 5, 4.52 CLR template is very old not updated

### ISSUE THREAD

**Issue by mach37** [ASP-NET-MVC-Boilerplate/Templates#145]
Hi, 

- Can you please update the templates 
- and give us options to simplify for e.g. remove DI or other features. with the same config UI screen like the RC Core version
- When will it have the ASP Identity included, if not there's a lot of manual work to integrate ASP Identity into this

thanks

**Comment by RehanSaeed** [comment]
I occasionally update the NuGet/JavaScript packages for the MVC 5 template. I personally don't have the time to add feature selection to it.

Regarding ASP.NET Identity, I'm now of the opinion that it does not benefit **everyone** to add this. Some people use IdentityServer4, Azure Active Directory (Both of these are preferred over ASP.NET Identity) or something else. That said, it does benefit a large proportion of people and it should be an optional feature that you can turn on.

Regarding feature selection, I rolled my own system for MVC 6. Microsoft is working on a new system called [dotnet new](http://rehansaeed.com/custom-project-templates-using-dotnet-new/). Adding features is a lot easier. I am currently using 'dotnet new' to to build a new API project template with Swagger and full feature selection. Eventually I will port the MVC 6 project template and in time, the MVC 5 one too which will also allow me to add feature selection to that too.

I have added a [TODO](https://github.com/ASP-NET-MVC-Boilerplate/Templates/projects/1), to the MVC 5 project to implement it using 'dotnet new'. If you wish, you can take a look at this repo and add a new MVC 5 template with ASP.NET Identity as an optional feature using 'dotnet new'. I will accept any PR's, as long as they benefit anyone using the template and are not too specific.

**Comment by mach37** [comment]
If we were that skilled we would not be using your templates :P  

Let me trying and get this working, and I will know if a PR merits something then.

On the Identity front, from the comments your target audience is mostly small mid dev's publishing their apps. However, both Azure, and IdentityServer(Now getting into consulting commercial) are more foused only only Azure hosting and commercial deployment - so I would argue against them, while leaving them as a option.

In the end my point is - your template is not a drop-in enchaining templates replacement - with the one single draw back of missing Identity and having to manually wire it up!

I like the DI stuff, but that should be an option as well - think about guys rolling out sites for corporate/gaming web sites, (I know - why people still do it with wordpress!!!)

**Comment by RehanSaeed** [comment]
If you follow my blog post you can get an MVC 5 project template built using 'dotnet new' pretty easily. I should point out that 'dotnet new' is still under development and will be released alongside VS 2017.

I don't disagree with you about ASP.NET Identity, I just think it should be a feature so it can be turned off by those who don't want it. ASP.NET Identity is very file heavy and it would take a lot of work to remove it manually.

Anyway, I've added a [TODO](https://github.com/ASP-NET-MVC-Boilerplate/Templates/projects/1), we'll see if I get the time to implement something or if I get a PR first. Thanks for your suggestion.
