### ISSUE TITLE
Typo in instructions

### ISSUE THREAD

**Issue by kfrancis** [ASP-NET-MVC-Boilerplate/Templates#149]
> 4. Run **dotnew** new bapi --name 'MyTemplate' along

should be

> 4. Run **dotnet** new bapi --name "MyTemplate" along

**Comment by kfrancis** [comment]
Specifically the dotnet command, but the quotes around the name actually produce a project and directory with quotes in them, and it's unbuildable.

**Comment by RehanSaeed** [comment]
Fixed. Thanks!
