### ISSUE TITLE
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error : [Browserslist] Could not parse E:\Visual Studio 2015

### ISSUE THREAD

**Issue by PDCS** [ASP-NET-MVC-Boilerplate/Templates#158]
I have this Error in which I am unable to publish to azruewebsites.net the local build and test are okay.
There are two npm warnings above the error could they be causing the [Browserslist] Could not parse?

> optipng-bin@3.1.2 postinstall E:\Visual Studio 2015\Projects\ParadiseClumberSpaniel\ParadiseClumberSpaniel\node_modules\optipng-bin
> node lib/install.js
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error :   √ optipng pre-build test passed successfully
> phantomjs-prebuilt@2.1.14 install E:\Visual Studio 2015\Projects\ParadiseClumberSpaniel\ParadiseClumberSpaniel\node_modules\phantomjs-prebuilt
> node install.js
Found PhantomJS at E:\Visual Studio 2015\Projects\ParadiseClumberSpaniel\ParadiseClumberSpaniel\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe ...verifying
PhantomJS is previously installed at E:\Visual Studio 2015\Projects\ParadiseClumberSpaniel\ParadiseClumberSpaniel\node_modules\phantomjs-prebuilt\lib\phantom\bin\phantomjs.exe
npm WARN EPACKAGEJSON paradiseclumberspaniel@0.0.0 No repository field.
npm WARN EPACKAGEJSON paradiseclumberspaniel@0.0.0 No license field.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error : [Browserslist] Could not parse E:\Visual Studio 2015\Projects\ParadiseClumberSpaniel\package.json. Ignoring it.

**Comment by PDCS** [comment]
Just ran http://jsonlint.com/ on package.json and it is okay
Stumped any ideas?

**Comment by RehanSaeed** [comment]
This could be gulp-mocha-phantomjs. Later versions do not like spaces in the file path. Use a file path without a space. There is an issue in the gulp-mocha-phantomjs repository that talks in more detail. I hope that helps. If they fix the issue, I'll update the template.

**Comment by PDCS** [comment]
Thank you: makes sense, I was wondering if I shouldn’t have spaces, some apps have trouble with that ..

 

~Peter
